// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5aptX5_xqxQ2fKz2f19SItwR_Z5d2HCY',
    appId: '1:166127006317:web:d645faaf548d2f40de0564',
    messagingSenderId: '166127006317',
    projectId: 'qaizen-car-rental-2023',
    authDomain: 'qaizen-car-rental-2023.firebaseapp.com',
    storageBucket: 'qaizen-car-rental-2023.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNeHhDpgD94UG727Z3UezXdGjwPqprBJg',
    appId: '1:166127006317:android:f116ec610e595407de0564',
    messagingSenderId: '166127006317',
    projectId: 'qaizen-car-rental-2023',
    storageBucket: 'qaizen-car-rental-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt8N18CMIypyugjnRmE2NkDmROauOyky8',
    appId: '1:166127006317:ios:dba83d5b494ed0bcde0564',
    messagingSenderId: '166127006317',
    projectId: 'qaizen-car-rental-2023',
    storageBucket: 'qaizen-car-rental-2023.appspot.com',
    iosClientId: '166127006317-v0cft509fp8p6uud1c6vvvntrvoip8ar.apps.googleusercontent.com',
    iosBundleId: 'com.qaizencarrental.qaizenCarRental',
  );
}
